server.port=8080

# Microservices Port Allocations
services.user.url=http://localhost:8081
services.otp.url=http://localhost:8082
services.assessment.url=http://localhost:8083
services.notification.url=http://localhost:8084
