server.port=8082

# H2 Persistent Database for OTP & Support Microservice
spring.datasource.url=jdbc:h2:file:./data/otp_db;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# H2 Console -> http://localhost:8082/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
